### ISSUE TITLE
wrong lat, long in cityIO json

### ISSUE THREAD

**Issue by andredaa** [CityScope/CS_cityscopeJS#1]
Latitude and Longitude are swapped in the table.json 
![grafik](https://user-images.githubusercontent.com/4631906/57869160-bbf35700-7804-11e9-8ad2-1e000b54cdd7.png)

The mapping in the table json know these different types
type	
0	"street"
1	"housing"
2	"housing2"
3	"working"
4	"working_2"
name	"grasbrook"

in the exposed json however there is also type 5, which doesnt match anything.

**Comment by RELNO** [comment]
@andredaa thanks for pointing this -- yes, this is a results of the way the table is now set in the lab and should be fixed in the final version. It's a result of the scanning interpreter looking upwards

**Comment by RELNO** [comment]
> The mapping in the table json know these different types
type
0	"street"
1	"housing"
2	"housing2"
3	"working"
4	"working_2"
name	"grasbrook"

For now these are placeholder types, as discussed these will be updated as objects so that one type would not matter
