### ISSUE TITLE
Repo Naming convention?

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#1]
What about having a naming convention here?

The naming convention sounds a bit too generic?  CS_CityScope is very redundant.

According to this structure (that BTW might need to be modified) https://github.com/CityScope/cityscope.github.io/wiki Isn't this repo linked to the scanning in JS?

**Comment by RELNO** [comment]
it's CS_CityScopeJS not CS_CityScope, and not 'very redundant'  in my view if this to become a library/npm tool. Also, it's no different from other repos with CS_xxx names. The naming doc was never meant to be restrictive after 'CS_' b/c you then can't have more than one tool per subject [i.e CS_SIMULATION]
