### ISSUE TITLE
502 bad gateway in viewing raw API

### ISSUE THREAD

**Issue by ChaoranChen** [CityScope/CS_cityscopeJS#10]
After I loaded the JSON file settings and drew the grid, the console showed the errors as follows:

> POST https://cityio.media.mit.edu/api/table/update/CityScopeJS 502 (Bad Gateway)

> (index):1 Access to fetch at 'https://cityio.media.mit.edu/api/table/update/CityScopeJS' from origin 'http://localhost:1234' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

when I checked the cityIO --> view raw API, the page showed:

>An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.
If you are the system administrator of this resource then you should check the error log for details.
Faithfully yours, nginx.

I have successfully open this page and saw the raw data before, but currently it shows the 502 BAD GATEWAY ERROR.

**Comment by RELNO** [comment]
Thanks for the issue. This is not a CityScopeJS issue but rather cityIO issue [the server side backend]. I'll restart the server and you should be up in ~5 min. For future issues of this kind, please add your issue to: https://github.com/CityScope/CS_CityIO_Backend/issues/46
