### ISSUE TITLE
Create agglomerated ABM layer  

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_cityscopeJS#10]
As discussed, aside from the moving agents vis, we need an aggregated version of ABM trips. 
Either on each update cycle (or less, depends of size), we should produce a static layer that shows meeting points/trips agglomerations. A simple starting point will be a heatmap, see  https://cityio.media.mit.edu/api/table/grasbrook/access for data format. 

We can visualize it in several ways:

![image](https://user-images.githubusercontent.com/14296774/68326786-1a094480-009a-11ea-8810-c555ff81b8dd.png)

![image](https://user-images.githubusercontent.com/14296774/68326809-21c8e900-009a-11ea-8a6c-7408b0cb0f0e.png)

**Comment by agrignard** [comment]
I really like the first visualization, I am thinking on how to do this with the GAMA team but it's not that straightforward. it is a kind of smart random offset to apply to the global trajectory

**Comment by RELNO** [comment]
done @ https://github.com/CityScope/CS_cityscopeJS/commit/1f4e83af064a7ad5c06bdb9cf3520ff60b04a108
