### ISSUE TITLE
Cannot close layer window from front end

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#104]
**Problem:**
After opening the Open Layer Window, it's not possible to close it and we cannot zoom anymore in the map (unless you relaod the page) 
<img width="1389" alt="Screenshot 2020-11-04 at 13 24 56" src="https://user-images.githubusercontent.com/3928502/98111618-28eb2880-1ea1-11eb-9d0a-93f48f53bab5.png">

**Solution**
I would assume that the user can close this layer with a button and also be able to zoom in the map to look closely their indicator

**How to reproduce it**
https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=dungeonmaster

**Comment by RELNO** [comment]
Cannot reproduce.. did you tried simply clicking on the map?

**Comment by agrignard** [comment]
Ok sorry may bad I am getting old I was looking for a button... it works when clicking on the screen but is it really intuitive? (maybe an additional button like a back arrow for old due like me can be complementary?) 

or what about keeping the possibility to scroll even if there is the toolbar? maybe a problem of focus?

**Comment by RELNO** [comment]
Possible, we did that for the champscope. here it was actually by design, since when you project on a table you'd prefer not to have pinned items over the map (i.e Temp Drawer API https://material-ui.com/components/drawers/#temporary-drawer)
