### ISSUE TITLE
Edit mode with high frequency indicator updates

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_cityscopeJS#106]
We might want to stop the indicator update in the front end when you enter edit mode. The way ABM indicators work in GAMABrix is that it starts posting information right away, even if it has not computed the whole simulation. That avoids huge lags in the front end between grid update and "I see the cool dots moving." The issue we're seeing is that when GAMABrix is posting new updates, the front end is refreshing like crazy and you cannot edit the grid.

I'll wait for @doorleyr to give me access to the modules VM and I'll setup a GAMA indicator in `dungeonmaster` to debug this.

**Comment by crisjf** [comment]
Here's a table that we can use to fix this:
https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=dungeonmodule

There's a GAMA module running in `csmodules` that is listening to updates from this table. 

As soon as you push an update to the grid, the module will start updating every few seconds and that will block any further updates to the grid until the simulation is completely done. 
![image](https://user-images.githubusercontent.com/8973959/98959585-6c611a80-24d1-11eb-9cc7-d80feab0d545.png)

**Comment by RELNO** [comment]
I've looked into it and not sure how to do that without deep refactoring the system (both FE & cityIO). The system is designed for one module update per each design intervention (you move a Lego brick, you get one compute cycle). What you're creating is torrent of results, disconnected from the actual edit. This has two issues: 1. your ABM hash in cityIO will always update, so that other endpoints will never know to which grid state you compute 2. you flood the FE with new data in a wannabe streaming way (which is not really, more like a GIF..) 

I feel we need to rethink this from the sim side, less so from the FE. Stopping update is not a real solution, it only hides the 'mess' in the cityIO side.

**Comment by crisjf** [comment]
Ok, this will be important also because it will inform how python brix will handle simulation-like indicators. 

I'll make sure that each complete simulation posts only two times, first quickly after the grid update to get rid of any front end lags that are annoying during demos, and second time with the full simulation results. Will this solve the issue?

**Comment by RELNO** [comment]
it will probably solve the FE issue, but less so the notion that a module only responds once to an edit. Think of it this way: if you have `crisAwesome` module that gets the last ABM sim results and do something with it, which hash are you looking for?

**Comment by crisjf** [comment]
How frequently do users build modules based on the results of other modules that they can access only through cityio? the only alternative that I see is to wait the 5 minutes or so that the simulation takes to run and post that, but then the front end user is waiting for 5 minutes for something. I think the problem of a long lag is more common than the bottleneck issue for modules. Or am I wrong?

If it does happen that there is a `crisAwesome` module waiting for the results of the ABM, I don't see an issue in the module updating twice, a quick first pass after the rough cut results from the simulation, and a longer more complex pass once all the simulation is uploaded to cityio.

**Comment by RELNO** [comment]
> How frequently do users build modules based on the results of other modules that they can access only through cityio?

Not a ton, but in fact we had it the other way around in Grasbrook/Corktown when at some point, ABM sim was only informed by another mobility module. I guess It is not so much about what we do now, more how we hope ppl will use this architecture in the future. 

> but then the front end user is waiting for 5 minutes for something.

True, but I'd then look back at why my module is computing for so long. We had a similar issue in Hamburg with noise simulation (that cannot stream like ABM does) and ended up simplifying it A LOT to get to a reasonable render time. Ronan's access module also creates "moving dots", in pretty much a fraction of this time, worth looking into it. 

Overall I'm fine with two bursts of data, but the above is worth remembering for future selves.

**Comment by crisjf** [comment]
I'll implement two bursts of data for now for GAMA but let's remember this in case someone wants to develop modules that rely on a GAMA module.
