### ISSUE TITLE
Need to edit grid twice for `GEOGRIDDATA` to work

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_cityscopeJS#108]
Here's how to reproduce the issue:

1. Create a new table at https://cityscope.media.mit.edu/CS_cityscopeJS/, and check `GEOGRIDDATA`, which is empty, and that's fine:
![image](https://user-images.githubusercontent.com/8973959/99994349-df4a7b00-2d86-11eb-90dc-f37b300ad069.png)

2. Edit a few cells and update grid. Then check `GEOGRIDDATA` again, not it's not empty, BUT it's still not complete (`id`s are missing, which breaks some modules)
![image](https://user-images.githubusercontent.com/8973959/99994418-f8ebc280-2d86-11eb-87de-e3159bd1f31d.png)

3. Edit a few cells again and update grid. Then check `GEOGRIDDATA` and you'll finally see the full object with ids:
![image](https://user-images.githubusercontent.com/8973959/99994495-128d0a00-2d87-11eb-87bf-af14fd4d1423.png)

Any chance we can edit `GEOGRIDDATA` just once?

**Comment by RELNO** [comment]
@crisjf great find. Fixed with creating IDs already on the editor, so new tables will have them by default. Also `GEOGRIDDATA` won't be empty anymore, so with each new grid, GEOGRIDDATA will be a mirror of GEOGRID
