### ISSUE TITLE
Adding a north orientation button

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#109]
I know it's an old problem/discussion that we always have but I am wondering if it make sense to add a "facing north" button in the interface to give the possibility to the user to be sure that the map is aligned with the north.

For now this introduce this issue in Gama https://github.com/CityScope/CS_Simulation_GAMA/issues/159 that might be fixed with the orientation variable. However it needs to be tested and will facilitate the integration if the map was already perfectly aligned

**Comment by RELNO** [comment]
done in new version
