### ISSUE TITLE
[Question] Can I make a new grid in a foreign country?

### ISSUE THREAD

**Issue by takesei** [CityScope/CS_cityscopeJS#113]
Hello!!

I'm trying to make a new grid using the CityscopeJS editor.
https://cityscope.media.mit.edu/CS_cityscopeJS/?editor

Since I want to try some simulators in my city, I inputted the (139.729563, 35.659369) in the latitude & longitude boxes.
However, when I tap the `center map` button with those values, Cityscope JS suddenly blackout (also, `create grid` button doesn't work either).
Does this app support to make a new grid in a foreign country?

Also, I checked this message below the projection box.
> Note: wrong projection might break app. Find the relevant projection at: https://epsg.io/

What's the projection? and how can I set them?

**Comment by RELNO** [comment]
Hi @takesei, 

Looks like it's a case of lat-long/long-lat flip, [which is a common issue with geosystems](https://stackoverflow.com/questions/18636564/lat-long-or-long-lat). The coordination system is there for edge cases, in which there's too much variance between the grid and the 'real' location. For most use cases, the current coordsys should be enough. 
For testing, I've flipped the coordinates and created your table https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=roppongi (which I assume deals with Roppongi Hills). Enjoy!
