### ISSUE TITLE
New description feature on Types Editor

### ISSUE THREAD

**Issue by guadalupebabio** [CityScope/CS_cityscopeJS#114]
In the Types Editor add a new feature that allows user to add comments/description of the use inputed.

**Comment by RELNO** [comment]
closed with 1f36e43a602d516689fdbab73be853390f2720bd. Add types info in editor. Note: will only be part of next version. 
<img width="281" alt="Screen Shot 2021-01-22 at 23 32 45" src="https://user-images.githubusercontent.com/14296774/105568809-3d092e00-5d0a-11eb-8ecf-eb1b07488445.png">
