### ISSUE TITLE
[Question] What's the 'proportion' in the TYPE?

### ISSUE THREAD

**Issue by takesei** [CityScope/CS_cityscopeJS#115]
Hello!!

When I read the `types` properties in `GEOGRID`, I found the property named `proportion`, and I'm not sure how this value makes any changes in CityScope system.
<img width="211" alt="Screen Shot 2021-01-23 at 18 47 57" src="https://user-images.githubusercontent.com/10820903/105575048-ff5ce180-5dab-11eb-90d6-0a6cec8cfd2f.png">

This topic isn't covered in the document (https://cityscope.media.mit.edu/docs/modules/Types%20System) (or maybe changing its name to "P" value??), so I'm a little confused.

Can you tell me what this is?

**Comment by RELNO** [comment]
@takesei thanks for your input. Indeed, our docs need more work..I'll add an issue to clarify this.

As you've discovered in https://cityscope.media.mit.edu/docs/modules/Types%20System, the "P" is indeed a proportion ratio of a sub-type within a type, and it should always be equal to 1 as described here:
![image](https://user-images.githubusercontent.com/14296774/105618824-c0358d00-5db9-11eb-8243-14f04e3b8f51.png)

Closing for now, will link this to CS docs.
