### ISSUE TITLE
Info option: add the possibility to render text as an output 

### ISSUE THREAD

**Issue by guadalupebabio** [CityScope/CS_cityscopeJS#119]
Add a new feature that allows the front end to visualize text (tips, suggestions, etc). It would be a similar to the radar or the bars but in this case printing text. Ideally, later can be added to Brix @crisjf. 
It should be located in the left part of the interface since it is an output of the simulation (below the radar in the image attached).
<img width="1440" alt="Screen Shot 2021-03-28 at 7 18 45 PM" src="https://user-images.githubusercontent.com/38555658/112771565-6c823280-8ffa-11eb-801d-f96282616e65.png">

**Comment by RELNO** [comment]
![Screen Shot 2021-03-28 at 11 09 53 PM](https://user-images.githubusercontent.com/14296774/112782401-ed512680-901a-11eb-9531-5c493e1ac3be.png)

See https://github.com/CityScope/CS_cityscopeJS/commit/6a01f3231ef57bf8802604e7c726a55330637141. if you add 'textual' module in this format:

```
 [{
 	"id": 450,
 	"info": "yes!"
 },{
 	"id": 40,
 	"info": "no!"
 }]

```
it will render text in the given grid cell.

**Comment by guadalupebabio** [comment]
This should be posted to `http://cityio.media.mit.edu/api/table/lomas/TEXTUAL` right?

**Comment by RELNO** [comment]
Correct, but note that this is a pre- published version.
