### ISSUE TITLE
Jitter aggregated ABM results 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_cityscopeJS#12]
To improve the visual result of the ABM aggeration, a jitter should be implement to either model or FE. I've created a simple example that adds random to paths: 
<img width="827" alt="Screen Shot 2019-11-18 at 16 56 11" src="https://user-images.githubusercontent.com/14296774/69111970-1dfb7600-0a4d-11ea-81bb-4cb2b3ff6d4a.png">

But for more fine tuned version we'll need this to correspond to actual OSM roads.

**Comment by agrignard** [comment]
What do you mean by "a jitter should be implement to either model or FE"?

In this case you add the random from the front end
https://github.com/CityScope/CS_cityscopeJS/commit/b41ea8db7826bd0d5b582d7fe8c945c3917bf0c4

I think I will soon have also have a version working from the ABM (but I need to test it and I don't know yet the time consumption it can introduce). 

If the frontend can handle it can be good to have actually the 2 option (either you visualise directly from the ABM if the ABM is noisy enough or you trigger the front end random if it's not)

However how do we spread the information if there is noise or not generated from the back end or the front end?

**Comment by agrignard** [comment]
This is what is produced directly from GAMA (the fuzyness and the deviation can be change as a global parameter).

I will try to push soon a version on cityIO to see how it looks

<img width="1163" alt="Screen Shot 2019-11-19 at 11 55 36" src="https://user-images.githubusercontent.com/3928502/69117833-9f8deb00-0ac3-11ea-8bbc-0d9d7893d943.png">

**Comment by RELNO** [comment]
> What do you mean by "a jitter should be implement to either model or FE"?

it means we don't want to have two places where the fuzzy effect takes place, so if GAMA is doing it, FE should not and vice versa. 

> However how do we spread the information if there is noise or not generated from the back end or the front end?

That's the problem, I can't. So we need to decide. I think GAMA should do it, since I'm not following any OSM path logic (it's really stupid random) but on your side this could show 'real' path finding fuzziness. 

> This is what is produced directly from GAMA (the fuzyness and the deviation can be change as a global parameter).

Looks good to me

**Comment by RELNO** [comment]
as this is done in one way or another, closing for now.
