### ISSUE TITLE
Parent Option in Types Editor

### ISSUE THREAD

**Issue by guadalupebabio** [CityScope/CS_cityscopeJS#120]
There might be some projects where there are categories, like TeraScope with Electricity, Sanitation, etc. A useful option would be to add the parent possibility after `Type` , this would allow the interface to group land-uses or as in my case technologies.
<img width="675" alt="Screen Shot 2021-03-28 at 7 28 15 PM" src="https://user-images.githubusercontent.com/38555658/112771831-bfa8b500-8ffb-11eb-9369-7b4164732ca4.png">

**Comment by RELNO** [comment]
given most table has maximal mun. of type <20, I think it is not crucial for now. I'll keep this in mind for future use cases.
