### ISSUE TITLE
(New) Toggle button in editor 

### ISSUE THREAD

**Issue by guadalupebabio** [CityScope/CS_cityscopeJS#121]
The scenarios feature is tied to the grid data update. To be able to have scenarios (e.g. "shared economy" yes/no) without interfering on the grid it would be really useful to add the possibility to create toggle buttons in the editor. Users would be able to customize certain parameters to influence the output of the simulation.

**Comment by RELNO** [comment]
there are a couple of issues to address before we can add this feature:
- cityio updates happen when the user is sending the grid via a button. How would these buttons/toggles send their interaction? If we let the user toggle and then wait until they already send the grid, the experience will be odd (toggle that does nothing)
- If we send right away, that means users will interact with the server every time they click. This will trigger a lot of updates on the modules sides, which might not be a desired outcome

**Comment by guadalupebabio** [comment]
- if the toggle appears in the View Option,  what it would need to do is to create a filter in the front-end that would modify the accessibility Analysis displayed, the radar, etc. I would create two indicators for each commit that would be filtered by the toggle (e.g. radar_now, rada_50years)
- if the toggle is modified before committing to city IO, then the simulation would only send one option. 

Both options are valid but the first one should be more intuitive for the user.
Both of the should limit the amount of commits.
