### ISSUE TITLE
Interface suggestion - Overflowing content on 'Grid Edit', 'Scenarios' and 'View Options'

### ISSUE THREAD

**Issue by guadalupebabio** [CityScope/CS_cityscopeJS#122]
Whenever there are too many types the user might not get to see the view options and scenarios. I suggest that each of them has fix dimensions and the containers use the [overflow](https://www.w3schools.com/css/css_overflow.asp) property. 
This is the case of the table that I am creating. Also, whenever the container cuts information it should be in the middle of the type to suggest the user that they should scroll down.
<img width="529" alt="Screen Shot 2021-03-28 at 7 54 16 PM" src="https://user-images.githubusercontent.com/38555658/112772536-62166780-8fff-11eb-9231-f69496ce9386.png">

**Comment by RELNO** [comment]
fixed in new version.
