### ISSUE TITLE
Toggle buttons not working in side pane

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_cityscopeJS#126]
All of the toggle buttons ('Aggregated Trips', 'Mobility Simulation' etc.) stop working during the session. This only started to happen very recently (in the past couple of days). The first time I press one of these buttons during a session it will work. But after this, if I try to press the same button or any other toggle buttons, they don't work (i.e. they stay in the same state). I have to refresh the page to get them to work again.

**Comment by RELNO** [comment]
Thanks, good catch. I've rebased to prev. commit to address the issue, but will have to refactor later to really fix. Problem is with an aging API for global state management that is getting very slow till total halt (which is what happened in this case). I'll deprecate it as part of CSjs 2.1 

Open if needed.
