### ISSUE TITLE
Cannot access cityscope.media.mit.edu/CS_cityscopeJS

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#13]
I am trying to access this url
````
https://cityscope.media.mit.edu/CS_cityscopeJS/?grasbrook
````
but it doesn't work could it be because I am in Vietnam?

**Comment by agrignard** [comment]
Sorry it is working now

**Comment by RELNO** [comment]
I won't be surprised if init the table will be quite slow. It's downloading ~10mb on init..
