### ISSUE TITLE
Bottom numbers not live-updating

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_cityscopeJS#130]
BTW, I noticed that the bar live updates but the number at the bottom does not update at the same rate. This is not a big deal at all but might confuse some people trying to debug their indicators. 

If anyone runs into this issue, just hit reload and the number will update.

![image](https://user-images.githubusercontent.com/8973959/116566355-afbf1200-a8d4-11eb-9f8f-b5e519b56b1b.png)

![image](https://user-images.githubusercontent.com/8973959/116566730-ff9dd900-a8d4-11eb-8c86-5d94f1ef1f16.png)

**Comment by crisjf** [comment]
I just realized that it eventually updates.

**Comment by RELNO** [comment]
yes, updates are pretty tied together for both https://github.com/CityScope/CS_cityscopeJS/blob/ef29336a6beaf6ad3e6e45c6da86a96351f54db8/src/views/CityScopeJS/VisContainer/BarChart/index.js#L89

**Comment by crisjf** [comment]
Feel free to close this. I can live with the small lag :)

**Comment by RELNO** [comment]
I'm in process of rebuilding data flows in the app, will keep this in mind
