### ISSUE TITLE
add GEOjson layer 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_cityscopeJS#131]
add geojson layer that can show different basemaps.

**Comment by RELNO** [comment]
@agrignard @popabczhang  please see https://github.com/CityScope/CS_cityscopeJS/blob/master/src/views/CityScopeJS/DeckglMap/deckglLayers/geojsonLayer.md for posting a geojson layer. it's very basic ATM, but we extend its capabilities as need be.  
![Screen Shot 2021-05-04 at 4 46 15 PM](https://user-images.githubusercontent.com/14296774/117067729-61f14200-acf8-11eb-80fd-f6dedf142cff.png)

**Comment by agrignard** [comment]
Great!
