### ISSUE TITLE
Cell size in meters or in square meters?

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_cityscopeJS#134]
This is a bit confusing and an easy fix. 

In the table constructor, it says the cell size should be specified in square meters, but it looks like the value given is really the length in meters of the side of the square cell. Which one is it?

![image](https://user-images.githubusercontent.com/8973959/118994608-7a966480-b954-11eb-9075-f494743be0af.png)

Is it 100m^2? meaning 10 by 10 meters? Or is it 100 by 100?

**Comment by RELNO** [comment]
I see why it can be confusing. It's 100 per side of the cell.

**Comment by RELNO** [comment]
solved with new version.
