### ISSUE TITLE
Cannot see the ABM2 layer

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#135]
In link with this issue
https://github.com/CityScope/CS_Simulation_GAMA/issues/163

I am trying to fix the sending from GAMA, The indicator and heatmap seems ok, the information in ABM2 seems to be ok too but I cannot see it i the browser (by activating the Mobility Simulation toggle)

@relno Do I have to change something in the string sent? This is what I have for the dungeonmaster table, i it the right format?
https://cityio.media.mit.edu/api/table/dungeonmaster/
https://cityio.media.mit.edu/api/table/dungeonmaster/ABM2

**Comment by RELNO** [comment]
<img width="586" alt="Screen Shot 2021-05-21 at 11 55 28" src="https://user-images.githubusercontent.com/14296774/119165454-7e48ea80-ba2b-11eb-9fc6-bcb8b310af8e.png">
Comparing with Corktown, it looks like you're posting ints instead of strings for mode & profile. 
Let me know if it's still broken afterwards

**Comment by agrignard** [comment]
Ok I changed to string.
What about this one? 
https://cityio.media.mit.edu/api/table/dungeonmaster/ABM2
I might still miss something (I don't see agent), maybe something related to the timestamps value?

**Comment by agrignard** [comment]
It's ok seems to rework!! Cool

This issue is still open as I don't send the header information 
https://github.com/CityScope/CS_CityIO/issues/128

**Comment by agrignard** [comment]
I am trying to access to this table to fix this issue but I see a white screen (seems to work for corktown)
https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=dungeonmaster/

Am i missing something?

This is what I get from GAMA , is there something wrong with the grid (the black cell)s?
<img width="737" alt="Screenshot 2021-05-26 at 14 18 25" src="https://user-images.githubusercontent.com/3928502/119658346-52fc3c00-be2d-11eb-8a9b-eb6785f55444.png">

**Comment by agrignard** [comment]
The ABM2 seems working I close this one which is now documented in https://github.com/CityScope/CS_cityscopeJS/issues/137
