### ISSUE TITLE
Problem with dungeonmaster

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#137]
Just for information/archive/documentation and maybe it will help to fix another issue

Something seems corrupted in the dungeomaster grid. 
https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=dungeonmaster/

I don't know exactly what but as some example and documenation are based on this guy (https://cityscope.media.mit.edu/modules/GAMA/), would it be possible to have it back?

Maybe we could agree also on a always running one for example documentation

**Comment by RELNO** [comment]
I see this when debugging. might be that Brix is sending null data or a rouge module. @crisjf, any thoughts? 
![Screen Shot 2021-05-26 at 12 58 55 PM](https://user-images.githubusercontent.com/14296774/119701267-28f14c80-be22-11eb-8ccb-15eb641e6861.png)

**Comment by crisjf** [comment]
The issue was with `GEOGRIDDATA`.

Not sure what happened though. I reset `GEOGRIDDATA` and it seems to be working now.

**Comment by RELNO** [comment]
Thanks @crisjf. I suspect this endpoint is used in the new grid maker iterations, which might have damaged it. At least for the time being @agrignard should use a unique end point for the class.

**Comment by crisjf** [comment]
I just checked the new grid-maker, but it doesn't seem to generate an error.

**Comment by crisjf** [comment]
@agrignard remember you can always rewrite the table with a fresh one using the web-app:

https://cityscope.media.mit.edu/CS_cityscopeJS/

**Comment by RELNO** [comment]
> I just checked the new grid-maker, but it doesn't seem to generate an error.

can you try a grid with transparent colors? I suspect it might have to do with that

**Comment by crisjf** [comment]
https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=new_dungeon

Seems fine to me

**Comment by RELNO** [comment]
Great, so I'll leave it as a randomly corrupted GEOGRIDDATA object. Will close for now.

**Comment by agrignard** [comment]
Ok new_dungeon is a new table so it works. but it could be interesting to know why and how dungeonmaster is dead and could have been corrupted no? Maybe the json was corrupted by hand indeed in this case there is few thing we can do indeed. There is no json content validator right?

Also if we remove it then some documentation needs to be updated as they are pointing to dungeonmaster

**Comment by crisjf** [comment]
@agrignard dungeonmaster was not dead when we closed the issue. Forget about `new_dungeon` that's a table I've bee using to test the new feature of creating a table from python using `brix`.

I haven't touched it since I left it running yesterday, so it is broken again, it might be something that GAMA is doing.

**Comment by crisjf** [comment]
`dungeonmaster` is up and running again.

Remember you can use the editor to recreate it if it ever breaks again:
https://cityscope.media.mit.edu/CS_cityscopeJS/#/editor
