### ISSUE TITLE
Case sensitive issue in the Grid Editor

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#138]
In https://cityscope.media.mit.edu/CS_cityscopeJS/#/editor

We need to make sure that the string is forced to lower case.

Right now if a user enter a name with a Capital Case the url will be in minor case which might make it difficult for the user to refind its table if he is using the initial string with a Capital Case

**Comment by RELNO** [comment]
Will add this in the upcoming version.

**Comment by RELNO** [comment]
should be solved in `detux` branch/ new version. Reopen if not solved.
