### ISSUE TITLE
Getting GRID and GRIDDATA slowly in the evening in GTM +7

### ISSUE THREAD

**Issue by n-h-tuan** [CityScope/CS_cityscopeJS#140]
I do not know the main reason why getting the GRID and GRIDDATA is so slow in the evening in Vietnam's Time (specifically, 7pm to 10pm), but in the morning, it just takes, maybe, 5 - 10 seconds to load everything.
Here is the table: hcm_scenario_0

**Comment by n-h-tuan** [comment]
Maybe this problem is from our Internet Providers, they reduce our bandwidth at this time.

**Comment by RELNO** [comment]
@nguyenledly thanks for letting us know. Usually these kind of issues are more relevant in https://github.com/CityScope/CS_CityIO or by pinging @yasushisakai. You can also use https://github.com/CityScope/CS_CityIO_uptime to track cityIO performance
