### ISSUE TITLE
How to erase a table on cityIO?

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#141]
With the refactoring of the cityIO, ones might to test some feature by creating a new table (e.g https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=test_arno), however ones the test is done ones might want to delete this table from cityIO

is there a way to do so?

**Comment by yasushisakai** [comment]
through the api you can, to de register the table fro the list.
https://cityscope.media.mit.edu/backend/API#delete-table

I thought there was a feature for this in the front end.

**Comment by agrignard** [comment]
Ok thanks, I should have read the doc ;-)
