### ISSUE TITLE
Connect a locally deployed cityIO

### ISSUE THREAD

**Issue by vbaryshev** [CityScope/CS_cityscopeJS#143]
Hello, please tell me how to connect a locally deployed cityIO server to the cityscopeJS module? When creating a new grid, it is now uploaded to the cityIO cloud server. 
Thanks for the reply.

local server cityIO:
1. redis-server
![Снимок экрана от 2022-01-08 18-28-06](https://user-images.githubusercontent.com/7428565/148653214-7af29975-1871-4e2d-91e5-a9da9f996621.png)
2. Doсker run cityIO, port 8040
![Снимок экрана от 2022-01-08 20-11-01](https://user-images.githubusercontent.com/7428565/148653278-717bc7ed-e371-4118-abd7-365b2474276f.png)

**Comment by vbaryshev** [comment]
> Hello, please tell me how to connect a locally deployed cityIO server to the cityscopeJS module? When creating a new grid, it is now uploaded to the cityIO cloud server. Thanks for the reply.
> 
> local server cityIO:
> 
>     1. redis-server
>        ![Снимок экрана от 2022-01-08 18-28-06](https://user-images.githubusercontent.com/7428565/148653214-7af29975-1871-4e2d-91e5-a9da9f996621.png)
> 
>     2. Doсker run cityIO, port 8040
>        ![Снимок экрана от 2022-01-08 20-11-01](https://user-images.githubusercontent.com/7428565/148653278-717bc7ed-e371-4118-abd7-365b2474276f.png)

**Comment by vbaryshev** [comment]
> Hello, please tell me how to connect a locally deployed cityIO server to the cityscopeJS module? When creating a new grid, it is now uploaded to the cityIO cloud server. Thanks for the reply.
> 
> local server cityIO:
> 
>     1. redis-server
>        ![Снимок экрана от 2022-01-08 18-28-06](https://user-images.githubusercontent.com/7428565/148653214-7af29975-1871-4e2d-91e5-a9da9f996621.png)
> 
>     2. Doсker run cityIO, port 8040
>        ![Снимок экрана от 2022-01-08 20-11-01](https://user-images.githubusercontent.com/7428565/148653278-717bc7ed-e371-4118-abd7-365b2474276f.png)

**Comment by RELNO** [comment]
Hi @vbaryshev - I'm not certain if that's the full solution, but probably a good starting point is to make sure CityScopeJS is looking for the redis URI/port. Currently  CityScopeJS is hard-coded to talk to CityIO URI on the web.  You can start by cloning, running locally, and changing the default url here https://github.com/CityScope/CS_cityscopeJS/blob/master/src/settings/settings.json.

**Comment by vbaryshev** [comment]
Thank you very much! With your comment, it turned out to move a little further into the deployment of a local project.
But for now, it is not possible to send data and save it in the database from CS_cityscopeJS to cityIO (Local running).
The server seems to be working correctly
![Снимок экрана от 2022-01-10 10-23-09](https://user-images.githubusercontent.com/7428565/148730500-56133dde-b2fd-4d70-9973-10df4a1fa846.png)

1. I changed the settings here, but I may have made a mistake in the path to the API table ~  /src/settings/settings.json. ?
![Снимок экрана от 2022-01-10 10-27-32](https://user-images.githubusercontent.com/7428565/148730871-b8ab589a-2a9c-4fbb-8069-fb913a69bcc6.png)

2. But when trying to save the grid, there is no process of exporting to the server and saving to the database.
![Снимок экрана от 2022-01-10 10-29-33](https://user-images.githubusercontent.com/7428565/148731150-ae07bc2c-f8d9-45c2-bbc0-8e2edb3badfa.png)

Thanks!

**Comment by RELNO** [comment]
I'm less familiar with how redis expects CRUD (I saw you're discussing that with @yasushisakai on another thread), but one simple thing before trying to implement it in CSjs, would be to test GET/POST reqs using `curl` to your redis db, as explained here: https://cityscope.media.mit.edu/backend/API. Can you post here the response for these calls? Also, please open the console and paste here the debug you get when you try to `commit grid to cityio`

**Comment by vbaryshev** [comment]
Hello, where is the sending of the data in cityIO I found, but how to fix it while there is no understanding (specify the correct path to the API tables of the local server)?
1. 
![Снимок экрана от 2022-01-10 10-23-09](https://user-images.githubusercontent.com/7428565/149210055-915342fc-566a-4637-99e4-1fc535f4f843.png)
![Снимок экрана от 2022-01-10 19-25-25](https://user-images.githubusercontent.com/7428565/149210614-4c59a551-6f99-4f06-9df8-2643518631c6.png)

2. I sent the request to another address, i thought this was my mistake, but it turned out to be the same with the correct name.
![Снимок экрана от 2022-01-10 19-45-22](https://user-images.githubusercontent.com/7428565/149210199-919e9d44-a054-402f-aa5c-3013e9353105.png)
3. Fixed to the server with this table name the data does not receive send.
![Снимок экрана от 2022-01-10 21-28-41](https://user-images.githubusercontent.com/7428565/149210275-c48bfe34-d6cd-4e59-82b3-60307dc8ce4a.png)

Thanks for the answer!

**Comment by RELNO** [comment]
Hi @vbaryshev -- I'm a bit struggling to understand the issue, let's see what I got so far:
- you managed to run cityIO locally
- you're able to `GET`/`POST` to cityIO via `curl` or any other way
- you're able to run CSjs locally
- you have already changed your local CSjs development copy so that all API pointers are reflecting the `localhost` / redis

Please confirm that the above is correct before moving forward.

**Comment by RELNO** [comment]
@vbaryshev I'm closing this since @doorleyr has built a new, lightweight cityIO replica (https://github.com/CityScope/cityIO_Flask) that will work well with the upcoming version of CSjs.
