### ISSUE TITLE
all CS repo? changing relno to githubuser in the jsons

### ISSUE THREAD

**Issue by tuxun** [CityScope/CS_cityscopeJS#15]
- in the json(s), put "github user" instead of "relno"
goal: help to identificate if a table on the server was just erased by a github user testing the apps with default settings or by a relno/MIT affiliated table

**Comment by RELNO** [comment]
will do, please PR and I'll accept

**Comment by tuxun** [comment]
have you done it? i was stuck in my mind bug: how can i make the difference between a setting json and a table output? is there table output json on github repos?

**Comment by RELNO** [comment]
https://github.com/CityScope/CS_cityscopeJS/commit/d1f9edd7de8cbbaed909c2e366eba34ef0fd3fb5
