### ISSUE TITLE
Updating grid view with CityScoPy data

### ISSUE THREAD

**Issue by cruz-lucas** [CityScope/CS_cityscopeJS#151]
Hey guys, I'm trying to replicate the project using lego bricks, scanning using CityScoPy.

I created the grid called "loon_test", in Rio, Brazil, and set every building type to be interactive with TUI, I'm scanning a table of mine and I see the data I scanned in with cityscopy change in the raw data online (cityscopy field). Great, so far so good. But where I'm supposed to see the interaction with the grid (the grid change based on the scanned data)? The "projection mapping" tab on the site doesn't load for me (google chrome and firefox), is that it or these are two separate problems? I'm supposed to change the GEOGRIDDATA field myself based on the cityscopy field and then POST request to the endpoint?

Great project, by the way, I'm very inspired to do very useful applications and contribute as much as I can.

**Comment by RELNO** [comment]
@lucasdearaujocruz thanks for your interest in the project. 
> But where I'm supposed to see the interaction with the grid (the grid change based on the scanned data)?

The grid you're scanning (happy CityScoPy works well for you!) is * not yet * converted to the online CSjs grid. I'm afraid that this is still WIP (@ThomasLengeling, I believe you looked into that) . In practice, we'd need to add a method that grabs that CSjs `GEOGRID` object, parse the `types`, and use these types to map the CityScoPy types. Then, you'd want to use this mapping to update the `GRIDDATA` types each time the TUI grid changes. Again, this is not yet in place, and if you're interested you can contribute this part!

>  The "projection mapping" tab on the site doesn't load for me (google chrome and firefox), is that it or these are two separate problems?

Better news here: the `detux` branch is a ~%95 rebuild and future version of csJS. I'm about to deploy it in production soon, but the projection mapping was working and rebuilt there. 
You can grab and run it locally, would also help debugging!

**Comment by cruz-lucas** [comment]
Great! Thanks for the answer. I'm about to push a commit to my forked repo of cityscopy that updates GRIDDATA. It works, but I'm still debugging it. It turns out that when I couple the GRIDDATA update with cityscopy regular scanning, it breaks the page (it goes blank) and I have to reload the page.

Anyway, I think we may close the issue, thanks for the clarifying!
