### ISSUE TITLE
Scale of radar chart axes should be fixed to 0:1

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_cityscopeJS#156]
Currently, the scale of the radar chart axes will change depending on the maximum and minimum value of the indicators. See image below of a radar chart where the indicators are all between 0.1 and 0.2.
<img width="427" alt="Screenshot 2022-09-09 at 13 56 40" src="https://user-images.githubusercontent.com/7722116/189414956-bde395cb-ab05-4dc0-aeea-359f28492e15.png">

The min and max of the axes should be fixed to 0 and 1.

**Comment by RELNO** [comment]
<img width="537" alt="Screen Shot 2022-09-09 at 3 55 09 PM" src="https://user-images.githubusercontent.com/14296774/189433205-1affb388-c31b-4e3e-acf8-70d8d1a9b5c4.png">

should be ok now
