### ISSUE TITLE
break default settings for avoid overwritting by mistake

### ISSUE THREAD

**Issue by tuxun** [CityScope/CS_cityscopeJS#16]
- comment the url of cityIO in code apps, and add a note like:"be sure to have an unique table name before use the mit cityio public server" above this commented url (for example in https://github.com/CityScope/CS_cityscopeJS/blob/master/js/CITYIO/cityio.js , the url is "hidden" line 69)

goal: remove the ability to run "potentials harmful to someonelse table" apps if users haven't seen this warning.
Apps without url just shouldnt run and should cry a warning to their user.
PS: add a note telling to set the server url and where in the installation instructions

**Comment by RELNO** [comment]
in the tradeoff of legibility vs messing a table every now and then, i prefer letting people reach a certain point where they see the app running without break. I do see an option to add a checker for already existing table in cityIO
