### ISSUE TITLE
Grid colors in projection mode only update on browser refresh (Windows, local)

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_cityscopeJS#162]
I have two browser instances running the Volpe table on a Windows machine with local cityIO: one instance on screen in normal mode and one instance projected onto table in projection mode. The projection mode is only showing the grid.

 If I update the grid using the on-screen browser and submit the edits, the grid colors do not update in the projected instance. If I refresh the table browser, only then the colors update.

Note: this issue doesn't seem to occur on my MacBook when using the remote server.

**Comment by RELNO** [comment]
I'll try to set up access to the remote machine later, but for now can you test the solution here: https://www.reddit.com/r/chrome/comments/jte9ca/how_to_keep_a_tab_active_in_the_background_in/

**chrome://discards/** in the machine and try to toggle off the discharge

**Comment by doorleyr** [comment]
Just tried that solution but I get the same behaviour.

**Comment by doorleyr** [comment]
Also, the TUI layer controls do update correctly. So the tab is still making API calls- not sure why it doesn't upgrade the grid.

**Comment by RELNO** [comment]
Should be solved now. TUI object caused conflict, but it seems working now.
