### ISSUE TITLE
Adapt from end Colors (Radar and heat maps) to Kent's-compatible palette color

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_cityscopeJS#163]
Hi, 

Is it possible to adapt from ent Colors to Kent's-compatible palette color? similar to the "Old Volpe table?". 

Remember in heat maps: "Red is bad, green is good".

Radar: "Blue is the new hope color", and green is the benchmark:

![CityScope-A-Data-Driven-Interactive-Simulation-Tool-for-Urban-Design](https://user-images.githubusercontent.com/19315213/197174302-3a155321-33c8-40f7-ae7a-2ac00af7eaaf.png)

If you show me where is in the code, I can try to play with it

Thank you so much and my apologies for the inconvenience

**Comment by agrignard** [comment]
I guess this is now solved thanks to #7b5804 and the new MIT Green Diffused RGB

**Comment by RELNO** [comment]
Great effort by everyone in the team!! So happy we reached this milestone 🎉 let's hold for NFF code review and then we can close the issue
