### ISSUE TITLE
KPIs Socio -Economical -Environmental 

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_cityscopeJS#164]
Hi Ronan, how difficult is to have, Socio -Economical -Environmental indicators as Kent is asking for?

I am thinking about using what you already have and show very simple indicators:

**Socio =** this can be measure by Proximity in distance to (Amenities). We can show an aggregated KPI, and, maybe the 3 or 4 most popular like Health, Parks, Education

**Economical =** this can be measure by If we fulfill the number of amenities needed for the existing population. We can show an aggregated KPI, and, maybe the 3 or 4 most popular like Banks, Office, Retail, Innovation (Co-working and Labs)

**Environmental =** this can be measure by the life work balance; If have 100% of people working in Kendall, that has a big reduction of CO2. Also walkable access to the daily amenities.  A 3rd KPI could be number and access to parks, or something extracted from the mobility model..., and maybe an aggregated KPI with all of this 3 together

Please, let me know your thoughts

Best regards 

Luis

**Comment by RELNO** [comment]
Probably more fitting @ https://github.com/CityScope/CS_Urban_Indicators
