### ISSUE TITLE
Extension of the Grid and Heat Map 

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_cityscopeJS#176]
The Heat map of Open space gets cut by the limits of the grid, There is the Small peninsula/Natural Park missing: 

<img width="913" alt="Screen Shot 2023-01-18 at 5 21 35 PM" src="https://user-images.githubusercontent.com/19315213/213308545-22b91eea-c1f7-48ec-9cbd-919cd735aece.png">

Can the grid and heat-maps get extended like in the red lines of the image bellow?:

<img width="1141" alt="Screen Shot 2023-01-18 at 5 18 44 PM" src="https://user-images.githubusercontent.com/19315213/213307905-6362516e-2627-4cce-aade-6ff439f826fb.png">

**Comment by RELNO** [comment]
heatmaps are now gridded. @doorleyr data can stay the same.
https://user-images.githubusercontent.com/14296774/213497466-5d88d79d-be23-4766-a72f-b2f81d4da70f.mp4

**Comment by RELNO** [comment]
heatmaps are now gridded. @doorleyr data can stay the same.

https://user-images.githubusercontent.com/14296774/213497708-13300068-f095-4e18-9c58-05170066bbb8.mp4

**Comment by RELNO** [comment]
@LAAP extension of the grid seems excessive as it's 95% water/marshland
