### ISSUE TITLE
Mobility Module is not working

### ISSUE THREAD

**Issue by Daaira0811** [CityScope/CS_cityscopeJS#182]
Hi, I am a student and I am trying to build a test instance for the CS_Spatial_modules module, however, the mobility module has errors with the current version of cityscopeJS, so I would like to ask about a version of the cityscopeJS module that works with Spatial Modules.
My tests were performed with the current version of cityscopeJS and Spatial Modules from its master branch.

**Comment by RELNO** [comment]
@Daaira0811 thanks for your interest in the project - modules are generally handled in the CS_Spatial_modules repo, and @doorleyr might be able to assist you.

**Comment by RELNO** [comment]
closing for now, reopen if CSjs relevant
