### ISSUE TITLE
Traffic Layer thickness

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_cityscopeJS#184]
Low trafficked roads are not currently visible in the traffic layer. Their thickness is determined by traffic level and many roads have extremely low traffic when compared to major highways.

Can the traffic layer thickness be determined by the 'lanes' property instead? This will ensure that smaller roads remain visible even when they have much less traffic than the major highways. The color should still be determined by the 'norm_traffic' property.

**Comment by RELNO** [comment]
let me know if that looks better. Can you also push the `lane` prop to the local cityIO? 


<img width="1161" alt="Screenshot 2023-01-25 at 12 18 50 PM" src="https://user-images.githubusercontent.com/14296774/214635089-d5b690a6-292e-4942-adec-e342aa13db9f.png">
<img width="976" alt="Screenshot 2023-01-25 at 12 19 06 PM" src="https://user-images.githubusercontent.com/14296774/214635097-2b7f1916-2c3c-4dfe-97d4-f2388fc27ea8.png">

**Comment by doorleyr** [comment]
The thickness looks much better here. The height seems a bit extreme to me, maybe can scale it down a bit?

**Comment by RELNO** [comment]
Sure. This is also controlled by the slides (increase the variation when values are similar)

**Comment by LAAP** [comment]
This is looking good, I actually like the Height, it gives a good sense of the differences of scales

Also, I think the Color ranking should be more fine grain, I see a lot of "green" "very high" roads. Can we use deep red in the big highway and yellow and orange in the rest, and only green-ish in the very small roads?

**Comment by RELNO** [comment]
@LAAP values are per 0-1 normalization, and most value are the lower bounds. When it comes to traffic, mostly green simply means not congested, right @doorleyr ? 
<img width="785" alt="Screenshot 2023-01-25 at 3 56 18 PM" src="https://user-images.githubusercontent.com/14296774/214688724-3015489e-a19d-43b7-b145-b8695663e35a.png">

**Comment by LAAP** [comment]
OK. I truly thing that we need to tell a story so people can understand. If **everybody is complaining about traffic in the community**, I think that it will be not understood by the community if we show that the only "traffic issue" is happening on the highway. All the heat maps and mobility maps are looking sooooo green and good in our tool... I think that It looks more like us making a "wrong calculation", than us been "scientifically accurate". But... I guess that this is your call

**Comment by doorleyr** [comment]
I double-checked that I'm processing the traffic data properly and the result is the same. Probably, the traffic data are over-representing highway trips and underrepresenting trips through the city. In order to tell the story better, I switched to only showing the delta in traffic for each scenario- this is doing a better job of highlighting the problem areas. It's not ideal but since we don't have reliable data, I don't see much else we can do for now.

<img width="1368" alt="Screenshot 2023-01-26 at 14 40 10" src="https://user-images.githubusercontent.com/7722116/214934102-f25d32a2-f053-49aa-98c8-4ac22d6ce8c7.png">
