### ISSUE TITLE
About projecting tables to TUI

### ISSUE THREAD

**Issue by SRobles97** [CityScope/CS_cityscopeJS#185]
Hi, i`m working trying to project a test table built using the CityScopeJS editor. I can successfully scan several patterns and categories so the geogriddata information updates correctly. I think i have everything i need to display the image in a table using a projector but using the "Project to TUI" function in CityScopeJS, appears a "Missing TUI object in CityIO" message in screen. Same thing happens when i execute other projects in the CityScopeJS platform. Do i need to perform another step to project the image as a TUI? 
Thanks in advance for your help.

**Comment by RELNO** [comment]
TUI (=tangible user interface) is a json object that tells the projected view how to react to inputs such as change of layer or background maps. The idea is that you would want to control this view not via mouse and keyboard as in CSjs main view, but with more `TUI` like features (buttons etc).
See here an example on how to send TUI data for you table. Do note that this is very experimental and will might change soon https://github.com/CityScope/CS_cityscopeJS/blob/master/devTools/cityio_events.ipynb
