### ISSUE TITLE
Trips Layer lines are almost invisible for some cities

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_cityscopeJS#32]
The Trips layer is almost invisible for some cities because the lines are too thin. The thickness looks ok for Grasbrook but for Corktown and Aalto, the lines are very difficult to see. This may be because of the zoom level difference. It may be possible to solve this by using a variable thickness which changes when the zoom level changes. Alternatively, the thickness could be a user input.

<img width="686" alt="Screenshot 2020-01-31 at 12 36 36" src="https://user-images.githubusercontent.com/7722116/73540534-14689400-4428-11ea-9c1a-df081cf6d3d3.png">

<img width="554" alt="Screenshot 2020-01-31 at 12 37 08" src="https://user-images.githubusercontent.com/7722116/73540538-17fc1b00-4428-11ea-9feb-c8218479ba69.png">

**Comment by RELNO** [comment]
<img width="547" alt="Screen Shot 2020-01-31 at 14 39 26" src="https://user-images.githubusercontent.com/14296774/73572580-286bc000-443f-11ea-9e6c-fdcb1f42f9c3.png">

Should be better now, lmk if still too thin. 
The agent movements in Aalto seems too fast, is that intentional?
