### ISSUE TITLE
match trips layer to new deckgl format 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_cityscopeJS#4]
Seems like deckgl updated `tripsLayer` format, so that new format follows: 
https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/trips/trips-v7.json

We currently use:

```
 "segments":[[10.009451311164248,53.53170222274841,250.0],[10.009420152886946,53.53170042111756,500.0]

```
in which the third item is timestamp. This is broken now.
https://github.com/uber/deck.gl/blob/master/docs/layers/trips-layer.md

**Comment by agrignard** [comment]
Should be fixed in this commit https://github.com/CityScope/CS_Simulation_GAMA/commit/ff440729ad7f6d46f16d0690fd7c1997499d8f85

@RELNO is it possible add a button to trigger on and off the ABM model to test it. the entry point is now tableName/ABM

**Comment by agrignard** [comment]
This one also need to be updated
https://github.com/CityScope/CS_cityscopeJS/blob/master/Grasbrook_GIS/layers_json/trips.json

**Comment by RELNO** [comment]
>  is it possible add a button to trigger on and off the ABM model to test it. the entry point is now tableName/ABM

At this point no, since the deckgl we use operates on a non-react env., as explained here: https://github.com/uber/deck.gl/blob/master/docs/api-reference/mapbox/overview.md#limitations

This is one more reason why, if we indeed need to depend on deck more, we should consider react.

**Comment by RELNO** [comment]
@agrignard https://cityio.media.mit.edu/api/table/grasbrook/ABM seems to have all timestamps set to 500 (so no movement at all) -- It's then hard to see whether the layer loads properly. Can you add some movement?

**Comment by agrignard** [comment]
done

**Comment by agrignard** [comment]
Any update on this one? Would it be possible to change the entry point to ABM in order to test it ?

**Comment by RELNO** [comment]
<img width="874" alt="Screen Shot 2019-10-16 at 16 22 59" src="https://user-images.githubusercontent.com/14296774/66923497-9677ad00-f031-11e9-9758-e5772b4c3f3b.png">
The layer is now functional -- however all `mode` are set to 2 -- is this intentional?
I can hardcode the new layer endpoint and deploy as soon as I'm back. If you want to test locally, change the endpoint here: https://github.com/CityScope/CS_cityscopeJS/blob/e64ba5dbfd50d03a25e3ca185cbf47e6a53423d0/scripts/abmLayer.js#L12

**Comment by agrignard** [comment]
I just want to test it on my personal computer (not the physical table) , no way to change the endpoint and commit it? 

Right now I just uploaded the pedestrian agents (2) but can and will be multi modal

**Comment by agrignard** [comment]
OK so I tried locally with the last commited version on the mastet and change L12
````
ABM: "https://cityio.media.mit.edu/api/table/grasbrook/trips"
````
by
````
ABM: "https://cityio.media.mit.edu/api/table/grasbrook/ABM"
````

I don't see anymore the trips but I don't see either the ABM when running

`````
http://localhost:1234/CS_cityscopeJS/?grasbrook
`````

**Comment by agrignard** [comment]
Ok so good news I see something but the rendering is not exactly the same (agents are really small) I guess we need to play a bit with the different parameters even if i don't understand why it's different

**Comment by RELNO** [comment]
Looking at your data, it looks like you've got 1-3 seconds steps. These will yield very short 'tails' and will move very slow. I suggest to go on 5 min intervals or so.

```
"timestamps":[33145,33146,33148,33150,33152,33176,33182,33198,33208,33217,33221,33228,33230,33232,33245,33275,33280,33283,33286,33291,33298,33301,33301]}

```

**Comment by agrignard** [comment]
this is the timestamps I produce in ABM (every 500 sec) from what I understand if we agree that 1 means 1 sec  then 64500sec is 18hour (from 6am to 12pm) to represent one day
`````
[500,1000,1500,2000,2500,3000,3500,4000,4500,5000,5500,6000,6500,7000,7500,8000,8500,9000,9500,10000,10500,11000,11500,12000,12500,13000,13500,14000,14500,15000,15500,16000,16500,17000,17500,18000,18500,19000,19500,20000,20500,21000,21500,22000,22500,23000,23500,24000,24500,25000,25500,26000,26500,27000,27500,28000,28500,29000,29500,30000,30500,31000,31500,32000,32500,33000,33500,34000,34500,35000,35500,36000,36500,37000,37500,38000,38500,39000,39500,40000,40500,41000,41500,42000,42500,43000,43500,44000,44500,45000,45500,46000,46500,47000,47500,48000,48500,49000,49500,50000,50500,51000,51500,52000,52500,53000,53500,54000,54500,55000,55500,56000,56500,57000,57500,58000,58500,59000,59500,60000,60500,61000,61500,62000,62500,63000,63500,64000,64500]
`````
In the trips layer the value are much more narrow 

`````
"timestamps":[26698,26699,26701,26703,26705,26743,26749,26765,26775,26784,26788,26794,26797,26797]}
````

**Comment by RELNO** [comment]
> In the trips layer the value are much more narrow

I'm not sure why the timestamps you produce in Gama do not match the timestamps in the triplayer data? There are 86400 sec a day,  you should match your trips to segments on this scale. Ergo: a trip from 0-300 will be a 5 min trip between 12:00:00-12:05:00 AM

**Comment by agrignard** [comment]
We agrred with Ronan to produce content from 6am to 12pm (assuming taht nothing interesting happen during the night)

So that make 64500sec is 18hour if the timestamsp is in sec then the ABM layer is write and then the trips should be modify and I guess the frontend also

@doorleyr what do you think? what is the value that you have in trips?

**Comment by RELNO** [comment]
@agrignard let's keep the timeframes on 24hrs. Rescaling the time is very error prone, as in the next project we might have a different time frame (nighttime events). The front end can easily have jumps over boring hours, but in terms of looping through the data it is better to keep the day 24*60*60. So if you start your sim at 6AM, start your first timestamp at 6*60*60.

**Comment by RELNO** [comment]
@agrignard latest build has new ABM layer -- closing for now, let's discuss enhancements offline.
