### ISSUE TITLE
edits are POSTed twice 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_cityscopeJS#40]
It appears that after grid/network edits, `POST`s happen twice. 
similar to https://www.freecodecamp.org/forum/t/problems-with-react-rendering-twice/268945

**Comment by RELNO** [comment]
@yzheng1998 can you take a look as to why `baseMap` renders twice when new `cityio` data arrives?

**Comment by yzheng1998** [comment]
I am not getting this behavior. Perhaps this is already fixed?

**Comment by RELNO** [comment]
yes, looks like it's solved
