### ISSUE TITLE
consolidate data formats 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_cityscopeJS#44]
`meta_grid` => `GEOGRID`

`interactive_grid_data` => `GEOGRIDDATA`: [] created via FE on tool init for the first time

`interactive_network_data` => `GEONETWORK`:[] 

`GEOGRID.properties` to include `header`: {}, `mapping` (name to be decided): {}

**Comment by doorleyr** [comment]
GEOGRID is done for Grasbrook and Corktown.
https://cityio.media.mit.edu/api/table/grasbrook/GEOGRID
https://cityio.media.mit.edu/api/table/corktown/GEOGRID

The grid_geojson module and examples are also updated with 15c6b9040a462fbbefddbf2944a15fe59eb7da4a so you can modify and create new grids if you want.
