### ISSUE TITLE
Cell Attribute in Full Grid and Interactive grid

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#5]
In order to feed the Micro ABM Model we will need to edit the usage of each cell for the full grid and the interactive one.

Right now the usage is the same for every cells. I don't know what will be the process to edit the landuse, for the interactive grid we can imagine to produce this file from the grid value. For the fullGrid we might have to use QGIS to create a static raster representation of the area.

https://github.com/CityScope/CS_cityscopeJS/tree/master/Grasbrook_GIS/layers_json

**Comment by RELNO** [comment]
Where do we need these two grids values to be edited? within GAMA? 
If so, the two grids are stored in cityIO :
https://cityio.media.mit.edu/api/table/__TABLE__/grid_full_table
https://cityio.media.mit.edu/api/table/__TABLE__/grid_interactive_area

Like any other field, these could be updated by any module.

**Comment by doorleyr** [comment]
I think what's missing from the information on cityIO right now is the baseline land use of each grid cell in grid_full_table. This is not such a big deal for Grasbrook as everything is industrial right now but for example, in the Ford project, the static grid cells all have different LUs.

One possible solution would be for the module that creates /grid_full_table to add the LU information by cross-referencing to LU maps:
https://amyvogel.carto.com/builder/929ca889-b29c-43bf-998d-1bef7edc30b7/embed
https://data.detroitmi.gov/app/parcel-viewer-2

The cells in the full_grid which correspond to cells in the interactive grid would have a usage of 'None' so that they are over-ridden by the interactive grid.

If this makes sense, I can work on doing this for both Detroit and GB with the grid_geojson module and post to cityIO.

**Comment by RELNO** [comment]
It might be tricky to subtract the active grid from the full grid if they do not 100% match (which was the case in Andorra). One way to go about it is to force the active grid to always fall inside the larger one. If we agree on that, than there should only be one grid per table with different attributes. A meta field in that grid will tell users what is the interactive zone(s).

**Comment by doorleyr** [comment]
Yeah I think that makes sense. I can edit the grid_geojson module to be able to create the meta grid. Then each cell will have an attribute of 'interactive': True/False. The interactive cells will also have an id corresponding to their index in the .../grid data. Makes sense?

**Comment by RELNO** [comment]
Sounds good to me. On front end, I assume the process to be: 
Get grid from cityIO => run over grid and make array of grid cells that are active 
then on each cityIO update:
run over interactive array => update

To sort this array in a non-random way, we'll need a serial # for each cell, do we already have that?

**Comment by doorleyr** [comment]
Yeah that's what I meant about the id corresponding to the index in ../grid_data. I will give the interactive cells a grid_data_id. So then we know that the interactive cell with id _j_ corresponds to the _j_th value in the list of grid data.

**Comment by RELNO** [comment]
great, that will make it easy to update grid.

**Comment by agrignard** [comment]
I was just mentioning to give a value for usage which is now always "usage":0. This can be done through different software like QGIS or why not GAMA, the question here is what do we want to put here. Right now it is full industrial but when a design will be proposed we will have different usage that will drive the micro ABM model and then potentiallay one grid_full_table per proposal

here https://cityio.media.mit.edu/api/table/__TABLE__/grid_full_table

We might want first to create one generic design that embedded all the possible cells usage  (Residential, Office, Park, etc..). We also need to agree on a specific standard

**Comment by doorleyr** [comment]
Ok a first iteration is done for Grasbrook here:
https://cityio.media.mit.edu/api/table/grasbrook/meta_grid
I can have the same for Detroit pretty soon.

This is just using the land uses that were in the GIS file ('industrial', 'brush') and 'None'. Of course we eventually need to agree on a standard list of land uses that we can use for both projects. For now let's try to converge on a format.

Let me know what you think of this format and suggest and any changes.

**Comment by RELNO** [comment]
@doorleyr thanks -- I understand that there's no change to the gejson library itself, only to the output?

**Comment by doorleyr** [comment]
@RELNO No I had to update the library (74434f1). I extended the grid class with some new methods to extend a simple grid to a composite grid and to cross-reference the cell locations with a land use geojson. See the updated examples.
It's backwards compatible so you should still be able to create a simple grid as before although I had to add 2 new dependencies: numpy and matplotlib.

@agrignard @RELNO the composite grids for corktown and grasbrook are now both available on cityIO. I'm still just using the land uses directly from the land-use maps I had available; eventually we need to agree on a list of accepted land uses.
https://cityio.media.mit.edu/api/table/grasbrook/meta_grid
https://cityio.media.mit.edu/api/table/corktown/meta_grid

**Comment by agrignard** [comment]
@doorleyr to keep the compatibility between cities what about putting at least the actual landuse in GrassBrook? Using the same terminology (https://data.detroitmi.gov/app/parcel-viewer-2) as in detroit so values among "M1,M2,M3,M4 and M5"

https://cityio.media.mit.edu/api/table/grasbrook/meta_grid

**Comment by doorleyr** [comment]
Ok, for consistency sake, I updates Grasbrook meta_grid to have the same codes (just 'M1' or 'None'). But as discussed, we will eventually need to agree on a mapping to LU codes that works for both projects.

**Comment by RELNO** [comment]
Let me just summarize what we're discussing here, since it involves quite a lot of changes:
- We move from 2 geoJSON grids to one; this affects both the scanner and the front end (will only implement after Mweek) 
- This grid is pre-populated with flag for interactivity 
- each cell also is pre-populated with initial land uses 
- all cells params could be edited by all modules 
- land uses are to be set in a discussion, but could be different for each table 

Is this along the lines of how you see it?

**Comment by doorleyr** [comment]
Regarding the 4th point, I was not thinking that any module would be able to update the grid cell attributes. I think that the meta_grid should be created just once and be a static representation of initial land uses. The grid updates would captured in the grid array as normal. Then, for example, the ABM (or any other module) would read the meta_grid data just once and continuously get updates from the grid array. Since the interactive cells of the meta_grid have an interactive_id attribute, the ABM knows which cells correspond to which entries in the array.

**Comment by RELNO** [comment]
> Regarding the 4th point, I was not thinking that any module would be able to update the grid cell attributes. 

Agreed, however I was under the impression that in some cases, ABM or other module will need to update some data even for non-interactive cells. For example, if the interactive area affects the density of workers in the non-interactive area. This case will require some change to the meta of static cells.

**Comment by agrignard** [comment]
@doorleyr can you differentiate the landuse in the grasbrook current table. right now we only have M, would it be possible to have M1 for the island and M2 for the rest, it will be easier to constrain the agent in the island area (now there are crossing the water as there is no way to differentiate the landuse)

**Comment by agrignard** [comment]
Just to be sure we are on the same page right now the usage filed is not corresponding to the interactive grid? But it will?

In 
`````
https://cityio.media.mit.edu/api/table/grasbrook/grid_interactive_area
`````
usage is always equal to 0

It will be necessary to customize the ABM model to know the landuse of the interactive grid

**Comment by doorleyr** [comment]
@agrignard I don't really understand the issue. The water has a Land Use of 'None' so this should prevent people from going into the water. Also, we already have the agents' home and work locations so presumably the other locations they need to choose are 3rd places which would not be on industrial land uses anyway.

I don't think artificially changing land uses is a good idea. At baseline, the land uses of the 2 peninsulas are the same. Without new buildings, there's no reason the agents should behave differently with respect to each peninsula. When new buildings are added to the interactive area, this should be what causes people to behave differently in this area.

**Comment by doorleyr** [comment]
Regarding the "grid_interactive_area", I think the idea is to eventually just have one grid which includes interactive and non-interactive cells (the meta-grid). So the 2 other grids would not be needed anymore at that point.

**Comment by agrignard** [comment]
This is to differentiate the 2 site, if I only show the agent form the macro model that's fine, but if we need to show something a bit more interesting than just the commuting so it's necessary to be able to differentiate some part of the area. So for instance some pedestrain could "hangaround" in a specific indutry and some other in the other one. Right now everything is the same so no way to differentiate it.

Ok so I'm ok if eveyrthing is in the metagrid but it will be larger to load

**Comment by agrignard** [comment]
btw there is only 10 interactive piece in grasbrook

**Comment by doorleyr** [comment]
> btw there is only 10 interactive piece in grasbrook

Are you talking about in the meta_grid? There are 100 interactive cells in the meta_grid. They are not all consecutive because if you list every grid_cell in order, there are breaks between the interactive cells in each row.

**Comment by doorleyr** [comment]
> This is to differentiate the 2 site, if I only show the agent form the macro model that's fine, but if we need to show something a bit more interesting than just the commuting so it's necessary to be able to differentiate some part of the area. So for instance some pedestrain could "hangaround" in a specific industry and some other in the other one. Right now everything is the same so no way to differentiate it.

I think it's fine to have extra people hanging around but not on industrial sites. At baseline, in Grasbrook the reality is that it's all industrial and nobody hangs around there. Once we start having other land uses in the interactive area (eg. commercial buildings or amenities), then we could have people hanging around that area.

**Comment by doorleyr** [comment]
As discussed, on creation of the metagrid I will also post to cityIO a dictionary which maps between the index of interactive grid cells to the index of grid cells in the metagrid.
I'll put it in /header/interactive_grid_mapping unless someone objects and wants it somewhere else.

**Comment by agrignard** [comment]
Ok for me let me knwo when it's ready in order to integrate the block type in the micro mobility model

**Comment by doorleyr** [comment]
I had problems posting to the header so I've posted to the objects field. It may be a better place anyway.
https://cityio.media.mit.edu/api/table/grasbrook/objects/interactive_grid_mapping
https://cityio.media.mit.edu/api/table/corktown/objects/interactive_grid_mapping

**Comment by agrignard** [comment]
Cannot access to this one
https://cityio.media.mit.edu/api/table/grasbrook/objects/interactive_grid_mapping

**Comment by RELNO** [comment]
> Cannot access to this one

CityScoPy sends meta table data to `objects` so probably a new scan cycle cleared whatever `objects` had before.

**Comment by doorleyr** [comment]
@RELNO can you update CitySCoPy so it doesn't do that? We can't have one module with a monopoly on the objects field. You can just post to '.../objects/cityscopy' so it doesn't delete whatever else is in '/objects'

**Comment by RELNO** [comment]
> We can't have one module with a monopoly on the objects field

The agreed module architecture is that each fields cannot have subfields (i.e __table__/f1/f2/f3...) to avoid endless recursiveness. Ergo, `objects` (or any other field) can only be governed by one module. In the past, `objects` was the place where the scanner posts additional types data (i.e, metadata of each type), so I'd suggest to keep it so. 
I therefore suggest that the dictionary will have it's own field.

**Comment by doorleyr** [comment]
> Ergo

Ergo?

Ok, posted to new field. @agrignard you can find them at:
https://cityio.media.mit.edu/api/table/corktown/interactive_grid_mapping
https://cityio.media.mit.edu/api/table/grasbrook/interactive_grid_mapping

**Comment by RELNO** [comment]
> Ergo? 

https://lmgtfy.com/?q=ergo&pp=1&s=g

**Comment by doorleyr** [comment]
> https://lmgtfy.com/?q=ergo&pp=1&s=g

I know the word. I just expect it from people who wear more tweed.

**Comment by RELNO** [comment]
https://getyarn.io/yarn-clip/f4186611-44ce-4873-a697-2cf4eee2fe9a

**Comment by agrignard** [comment]
> > Ergo
> 
> Ergo?
> 
> Ok, posted to new field. @agrignard you can find them at:
> https://cityio.media.mit.edu/api/table/corktown/interactive_grid_mapping
> https://cityio.media.mit.edu/api/table/grasbrook/interactive_grid_mapping

I can access it

**Comment by RELNO** [comment]
looks like this is a `NORMAN-LIZATION` discussion which happens elsewhere now. closing.
