### ISSUE TITLE
TUIgridData error

### ISSUE THREAD

**Issue by yzheng1998** [CityScope/CS_cityscopeJS#55]
When initiating app @ http://localhost:3000/?cityscope=grasbrook

![image](https://user-images.githubusercontent.com/31601104/75277129-71f8c200-57d5-11ea-9869-56442f4f85ff.png)

The issue comes from
_proccessGridData in baseMapUtils.js, with the line:
`let cellValueByIndex = Object.values(types)[TUIgridData[i][0]];`

This is because when `TUIgridData[i][0]` is greater than 4, then there is no type to match it, which is due to the fact in the Type Options Editor PR, 8 or so types have been merged down to 5 (Types 0 thru 4). To temporarily fix this problem, I added a dummy type such that when `TUIgridData[i][0]===5`, the build doesn't error out. I believe the only way to truly fix this problem is to clear the TUIgridData, or to potentially restrict accepted TUIgridData types to 0 thru 4.

```
"types": {
            "0": {
                "height": 0,
                "color": [128, 128, 128, 180],
                "name": "Clear Buildings",
                "class": "buildingsClass"
            },
            "1": {
                "height": 1,
                "color": [236, 195, 11, 180],
                "name": "Plaza",
                "class": "buildingsClass"
            },
            "2": {
                "height": 10,
                "color": [153, 213, 148, 180],
                "name": "Park",
                "class": "buildingsClass"
            },
            "3": {
                "height": [0, 10],
                "color": [252, 141, 89, 180],
                "name": "Residential",
                "class": "buildingsClass"
            },
            "4": {
                "height": [0, 80],
                "color": [50, 136, 189, 180],
                "name": "Office Tower",
                "class": "buildingsClass"
            },
            "5": {
                "height": 0,
                "color": [0, 0, 0, 0],
                "name": "Dummy",
                "class": "buildingsClass"
            }
        }
```

**Comment by RELNO** [comment]
@yzheng1998 understood, thanks. To clear `GEOGRIDDATA` (or any field) you can **carefully** use the `clear` API on cityIO: https://github.com/CityScope/CS_CityIO/wiki/API#delete-module-data
Note not to clear the whole table, but only the field in question. Another option to clear a field is to post an empty data to it: `POST https://cityio.media.mit.edu/api/table/update/:tableName/:moduleName`

**Comment by RELNO** [comment]
fixed @ https://github.com/CityScope/CS_cityscopeJS/commit/0efe10f8ce78c27fde45ddb9ea847ebd31475781
