### ISSUE TITLE
Run CityScopeJS on Detroit

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#6]
I am trying to visualize the results of the micro ABM on corktown

Trying this url doesn't work

`````
http://localhost:1234/CS_cityscopeJS/?corktown
`````

What are we missing here? Maybe some meta information in the grid.json?

**Comment by RELNO** [comment]
There are no grid fields for this table, see https://cityio.media.mit.edu/api/table/grasbrook for `grid_full_table` + `grid_interactive_area`. To init a table properly, use latest cityscopy revision

**Comment by RELNO** [comment]
closing for now.

**Comment by agrignard** [comment]
So I would suggest to leave this issue open until we make it work.

The grid exists in the meta_grid for detroit so I guess it's not that difficult to create the full_table and the interactive one from here (even if for now there is no real interactive area in detroit)

Also I think  we should give the possibility to visualize information even if there is no interactive grid. We might have model that will be interested to visualize for specific cities where there is no interactive area. 

@doorleyr  can you create in the same way as the hamburg one the detroit grid?

**Comment by RELNO** [comment]
>  The grid exists in the meta_grid for detroit so I guess it's not that difficult to create the full_table and the interactive one from here (even if for now there is no real interactive area in detroit)

As mentioned in https://github.com/CityScope/CS_cityscopeJS/issues/5#issuecomment-543391585, `meta_grid` is not recognized by the frontend as we never agreed upon the way we want to use grids. Till now, we discussed 2 grids for each table (with Andorra as the extreme case of 2, unaligned grids). I'm in favor of 1 grid with `interactive / non` attributes, but we need to agree on that.  

> Also I think we should give the possibility to visualize information even if there is no interactive grid. We might have model that will be interested to visualize for specific cities where there is no interactive area.

agreed.

**Comment by doorleyr** [comment]
The 2 (grids grid_full_table + grid_interactive_area) are now there on cityIO for Corktown but it still doesn't work so looks like that's not the problem. I guess CS_CityScoPy does some other initialisation that is necessary. @RELNO What else do we need to initialise to make it work?

**Comment by RELNO** [comment]
<img width="690" alt="Screen Shot 2019-10-18 at 10 22 28" src="https://user-images.githubusercontent.com/14296774/67102315-43b50700-f191-11e9-8224-6b7a73c77b11.png">
https://cityio.media.mit.edu/api/table/corktown is missing header & spatial data. This can be produced via cityscopy scanning -- you only need to scan once to get these fields in cityIO. make sure you edit the ___corcktown_settings___.json to match the site specs.

**Comment by doorleyr** [comment]
Ok I initialised the header data including spatial data. The site now loads and shows the 2 grids but the simulation is not shown. There is also an error because the front_end is expecting accessibility analysis data to be available. Could that be preventing the simulation from loading?

**Comment by RELNO** [comment]
<img width="886" alt="Screen Shot 2019-10-18 at 11 05 45" src="https://user-images.githubusercontent.com/14296774/67105689-40247e80-f197-11e9-9669-70f85f83ea44.png">

Sim is there, the access layer is not blocking. The new sim endpoint is not yet deployed to GH pages, but it is in the last commit. Run locally with parcel and see the sim.

**Comment by doorleyr** [comment]
Ok when I run it locally I see that the trips layer is there. But there's something wrong: it doesn't look like your screenshot. There's just a few barely-visible line segments that sort of flicker.

@agrignard is it working for you?

**Comment by RELNO** [comment]
My screenshot is with trails set to 10000. This is due to @agrignard 1 sec trips intervals discussed at #4.

**Comment by agrignard** [comment]
Ok working for me we now just need to agree together on #4
