### ISSUE TITLE
Optional viz window (and grid)

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_cityscopeJS#6]
The window that shows the colors that are currently being recognised is very useful during setup but for very large grids, displaying this is computationally heavy and increases letency. A nice enhancement would be the option to view this window during setup but then kill it when it's no longer needed.

To a lesser extent, this also applies to drawing the canvas containing all the grid points. Eventually, there could even be a headless mode where (if the keystone points are already saved in cache), you could run the scanning and sending without any visual feedback.

**Comment by RELNO** [comment]
done @https://github.com/CityScope/CS_cityscopeJS/commit/846189bd046263d994ab448a8aaec591e80901e3
