### ISSUE TITLE
Cells with attribute interactive:false should not be possible to edit using web interface

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_cityscopeJS#63]
The Corktown GEOGRID properties and GEOGRIDDATA has many cells with the property {interactive: False}. Currently, these cells can still be edited on the front-end. As far as I understand, it should not be possible to edit these cells. @RELNO If this is not the case, please tell me how to make some cells non-editable.

**Comment by RELNO** [comment]
I've did a little experiment (see #64 ) : I removed `GEOGRIDDATA` so I only get the grid. The outcome is the same as the one you can see @ #64. So it looks like it comes into data `GEOGRID` holds.

**Comment by doorleyr** [comment]
Closing this as it seems to be the same as #64
