### ISSUE TITLE
Toggle between access variables

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_cityscopeJS#65]
Frontend needs to be able to toggle between different access variables defined as properties of the features of the following geojson: 
https://cityio.media.mit.edu/api/table/table_name/access

(take https://cityio.media.mit.edu/api/table/corktown/access as an example)

The relevant line that selects the variable seems to be:
https://github.com/CityScope/CS_cityscopeJS/blob/c493003dd34721b926a75709963b7a34240e0ff7/src/components/baseMap/baseMapUtils.js#L190

For corktown, for example, it is not clear which access variable is being plotted here:
![image](https://user-images.githubusercontent.com/8973959/77795826-93eb9b80-7044-11ea-833c-625d370fae7f.png)

**Comment by crisjf** [comment]
See discussion in:

https://github.com/CityScope/CS_Urban_Indicators/issues/8

**Comment by doorleyr** [comment]
@RELNO this should be good to go from our side. Let me know if there is any issue with the format.

https://cityio.media.mit.edu/api/table/corktown/access

**Comment by RELNO** [comment]
I'm closing this in favor of progress at #66
