### ISSUE TITLE
Add a way to visualize the type of the Agent

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#7]
Right now there is a new field called "type" in
`````
https://cityio.media.mit.edu/api/table/grasbrook/ABM
``````
Representing the type of the agent according to this standard
https://github.com/CityScope/CS_Mobility_Service

Woudl be great to have a toggle to visualize it from the frontend.

**Comment by RELNO** [comment]
done @https://github.com/CityScope/CS_cityscopeJS/commit/159f684ff5c7c697df0a16a53ea81bdca28f6d2f
