### ISSUE TITLE
Add energy bars and reference indicators to Indicators data viz

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_cityscopeJS#72]
As discussed with @RELNO and @LAAP, the following features (as shown in the attached mock-up) should be added to the indicators data visualisation:
(i) "Energy bars": The indicators for the energy bars and radar chart will be read from the same list stored in the /indicators end-point. The 'type'  attribute will indicate whether an indicator should be added to the radar chart or the energy bar chart.

eg.
 [
{"type": "radar", "category":"innovation","name":"District-knowledge","values":[0.5, 0.75]},
{"type": "bar", "category":"innovation","name":"City-skills","values":[0.55, 0.3]},
...
]

(ii) It should be possible to display indicators for more than one scenario (eg. current table design and a reference city and/or a baseline scenario) in the indicator charts. We should also include the names of the different scenarios somewhere in the /indicators end-point. For example, we could put the list of indicators and the list of scenario names inside an object:

{'scenarios': ['existing', 'proposal'],
'indicators': [
{"type": "radar", "category":"innovation","name":"District-knowledge","values":[0.5, 0.75]},
{"type": "bar", "category":"innovation","name":"City-skills","values":[0.55, 0.3]},
...
]
}
In the above example, the value of 'District-knowledge' is 0.5 in the 'existing' scenario and 0.75 in the 'proposal' scenario.

![Picture1](https://user-images.githubusercontent.com/7722116/80092839-63bbed80-855b-11ea-930c-1f45a256e09f.png)

**Comment by LAAP** [comment]
All @doorleyr 's comments sounds good to me

**Comment by doorleyr** [comment]
The corktown indicators now all have a 'viz_type' property so the bar chart can now be created:
https://cityio.media.mit.edu/api/table/corktown/indicators

**Comment by doorleyr** [comment]
To follow on from discussion with @RELNO earlier, energy bars are looking good but right now, all indicators are appearing on both plots. Instead we should see indicators with "viz-type"="radar" on the radar chart and with "viz-type"="bar" on the bar chart.

Also, can we change the name 'urban matrices' to 'Urban Indicators' in the sidebar? @LAAP would you agree?

**Comment by RELNO** [comment]
<img width="1150" alt="Screen Shot 2020-04-30 at 10 49 17" src="https://user-images.githubusercontent.com/14296774/80724820-472a3300-8ad0-11ea-93b2-ad3c2434ae7d.png">

done in the PR commit

**Comment by RELNO** [comment]
<img width="416" alt="Screen Shot 2020-04-30 at 10 54 03" src="https://user-images.githubusercontent.com/14296774/80725329-ecdda200-8ad0-11ea-965b-4d074bfbaf29.png">

@doorleyr @LAAP sounds better to me as well

**Comment by LAAP** [comment]
@RELNO , It is looking fantastic!

**Comment by LAAP** [comment]
@RELNO @doorleyr , Yes, I agree "Urban Indicators" is perfect.

**Comment by RELNO** [comment]
@doorleyr can you run the module for GB as well? currently the data there don't align to the new FE bar chart

**Comment by doorleyr** [comment]
It should be possible to have both scenario indicators and reference indicators on the same plot. As shown in the original issue above:

> ![Picture1](https://user-images.githubusercontent.com/7722116/80092839-63bbed80-855b-11ea-930c-1f45a256e09f.png)

eg. 
If every indicator  is formatted contains both 'value' and 'ref_value' as in the example below, then the radar plot should have a 'reference' radar and a 'scenario' radar. Similarly the bar plot should have 'reference' bars and 'scenario' bars. There should also be a color legend to identify which is 'scenario' and which is 'reference'.
'''
{
    "category": "innovation",
    "name": "Skills",
    "raw_value": -8.261598409789132,
    "units": null,
    "value": 0.7034910536555334,
    "ref_value": 0.5
    "viz_type": "bar"
  }
'''

**Comment by RELNO** [comment]
closed with V2
