### ISSUE TITLE
Color trajectories by mode of transport and add a legend

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_cityscopeJS#79]
The trajectories in the /ABM end-point have a mode property, which is a list of length 2. 
mode[0]  represents the mode of transport for the trip (0:drive, 1:cycle, 2:walk, 3:pt, 4:shared micromobility, 5:shuttle bus)
mode[1] represents the type of person(commute in, commute out or live_work). 

The trajectories in the deckGL layer are currently given one of three colors based on the person type (mode[1]). However, it's more important to show the mode of transport (i.e. mode[0]) . I suggest the following color scheme:

0:[228,26,28];
1:[55,126,184];
2:[77,175,74];
3:[255,255,51];
4:[152,78,163];
5:[255,127,0];

I've already implemented this in my local so I can do a PR for this part if you want.

We also need a simple legend to understand these colors.

**Comment by RELNO** [comment]
>  (0:drive, 1:cycle, 2:walk, 3:pt, 4:shared micromobility, 5:shuttle bus)

Where is this list coming from? do we have it on each table the same from now on? If not, it might be better to rethink the data struct so we can populate more diverse modes/ppl. This will also affect a legend

> I've already implemented this in my local so I can do a PR for this part if you want.


Sure -- pull before though, since there are quite a lot of changes since yday

**Comment by doorleyr** [comment]
> Where is this list coming from? do we have it on each table the same from now on? If not, it might be better to rethink the data struct so we can populate more diverse modes/ppl. This will also affect a legend

This is the list of modes for Corktown. Yes, it probably makes more sense to include the mode details as a field specific to the table. Assuming there are N possible modes, we could have a list of length n:
[{'name': 'drive': 'color': [255, 0, 0]},
{'name': 'cycle': 'color': [0, 0, 255]
...}
We could add this to the GEOGRID header? We could also change the /ABM endpoint to be and object with 2 keys: one for the mode details (as described above) and another for the actual trajectory data. But this would be a breaking change which we should coordinate. What do you prefer?

> Sure -- pull before though, since there are quite a lot of changes since yday
I've done a PR so we can have something working for now. Btw, we now have multi-modal trips in the /ABM for Corktown, which should be visible with this update. eg. walk->bus->transfer->bus-walk

**Comment by RELNO** [comment]
> But this would be a breaking change which we should coordinate. What do you prefer? 

I guess we would want this all in one place. Yes, it will break GB, but we can redo GB. 

> [{'name': 'drive': 'color': [255, 0, 0]},
{'name': 'cycle': 'color': [0, 0, 255]
...} 

If we go with changes, let's make it very explicit: 

```
{
    "mode": {

--> HEX colors      drive: "#FFF"
--> explicit goal      goal: "home" 
    },
    "path": [
      [
        -83.064993,
        42.3353029
      ],
      [
```

**Comment by doorleyr** [comment]
There are two issues with doing it the explicit way above. One is that the trajectory data are already very large and sometimes the packages are even rejected by city_io for being too large. If we replace the integer representing mode with the full description, it will get much larger unnecessarily. Especially if we have multiple categories (i.e. mode, goal) as you suggest.

Secondly, when producing the legend, you would have to iterate through every record to find the set of all modes and goals. It will be much easier for the FE to just have a list of the modes/goals in one place.

I like the idea of being able to categorize trips by a "goal" though. We could also imagine having other color categories. eg. we could color people by "people profiles". (i.e. 9-5er, student etc.). One way to frame this to be more general and allow N ways of categorizing agents would be:
```
{
"category" : [0, 2, 3],
"path": [
      [
        -83.064993,
        42.3353029
      ],...
]
"timestamps": [1,2,3 ...]
}
```
where the N ids in category are explained by a static list of N definitions. eg:
```
[
  [
    {
      "name": "drive",
      "color": "#F00"
    },
    {
      "name": "cycle",
      "color": "#00F"
    },
...
  ],
  [
    {
      "name": "work",
      "color": "#F00"
    },
    {
      "name": "shopping",
      "color": "#00F"
    },
...
  ],
  [
    {
      "name": "9-5er",
      "color": "#F00"
    },
    {
      "name": "student",
      "color": "#00F"
    },
...
  ]
]

```

**Comment by RELNO** [comment]
it looks like we strongly need a dictionary, so we can avoid all the repeated colors, and other attr. that could be stored somewhere else. So:

```
{
    "attr": {
        "profile": { "Carole Baskin": "#81FF", "Joe": "#7f67" },
        "goal": {
            "home": "#1FF",
            "zoo": "#281F",
            "jail": "#89FF",
            "kill husband": "#561F"
        },

       ..... ANY OTHER ATTR......

        "trips": [
            {
                "mode": [0, 0],
                "path": [
                    [-83.0723807, 42.34099439999999],
                    [-83.0723504, 42.3409416],
                    [-83.07231759999998, 42.3408842],
                    [-83.07194399999999, 42.3402318],
                    [-83.07191879999998, 42.3401875]
                ],
                "timestamps": [35683, 35692, 35693, 35693, 35703]
            }
        ]
    }
}
```

Also to save space, all attr can become single letter trips=>t, path=>p

**Comment by doorleyr** [comment]
I made a new temporary end-point /ABM2 so that we can test this and when we're satisfied we can switch back to using /ABM.

We now have /ABM2/trips which contains the normal DeckGL trips format with two attributes: "mode" and "profile".
https://cityio.media.mit.edu/api/table/corktown/ABM2/trips

We also have /ABM2/attr which explains the possible values for each attribute. This should be used to create the legends:
https://cityio.media.mit.edu/api/table/corktown/ABM2/attr

Let me know if there is any issue with this.

**Comment by doorleyr** [comment]
The mode legend should update when the data in "/ABM/attr" change. This will allow us to have a percentage displayed which updates when new results are available. eg. the attr may contain as object as follows where the names change dynamically:
'''
{
  "mode": {
    "0": {
      "color": "#e41a1d",
      "name": "Drive 80%"
    },
    "1": {
      "color": "#377eb8",
      "name": "Cycle: 5%"
    },
    "2": {
      "color": "#4daf4a",
      "name": "Walk: 5%"
    },
    "3": {
      "color": "#ffff33",
      "name": "Public Transport: 6%"
    },
    "4": {
      "color": "#984ea3",
      "name": "Shared Micro: 2%"
    },
    "5": {
      "color": "#ff7f00",
      "name": "On-demand Shuttle: 2%"
    }
  }
}
'''
Alternatively, I could add the % as a new attribute (float) and you could display it on the FE whichever way you prefer.

**Comment by RELNO** [comment]
@doorleyr I can't see the other ABM2 endpoint, it might got deleted in the latest cityIO reset. 
In any case, how about this structure:


```

{
    "props": {
        "dict": { "m": "mode", "p": "paths", "t": "timestamps" },
        "mode": {
            "0": {
                "color": "#e41a1d",
                "name": "Drive 80%"
            },
            "1": {
                "color": "#377eb8",
                "name": "Cycle: 5%"
            },
            "2": {
                "color": "#4daf4a",
                "name": "Walk: 5%"
            }
        }
    },
    "tripsData": [
        { "m": [4, 0], "p": [[], [], [], [], []], "t": [1, 2, 3, 4, 5, 6] }
    ]
}


```

**Comment by doorleyr** [comment]
/ABM2 should be back now. The structure you showed above is fine for this project as the priority is to show modes. However, do we want to allow for other properties to be used for the color and legend? eg. in the /ABM2 data, I have given every trip 2 attributes: mode and profile. I also put the mappings for both of these attributes in the /ABM2/attr field. There could therefore be an option on the FE to switch between either categorization? If this is too complex for now, we can just focus on the mode.

**Comment by RELNO** [comment]
- A few questions on ABM2: 

- in trips, `mode` & `profile` are strings, can they be int? 
- in `attr` you use array for mode & profile; a key value (name:color) looks to me easier to read/handle. I know it will grow the size of the package, but for that we can do one letter as ket ("h" for homemaker) and in `attr` add a simple dict to translate one letter to full name.

**Comment by doorleyr** [comment]
> * in trips, `mode` & `profile` are strings, can they be int?

In the trips data, I could use ints for mode and profile. However, these numbers act as ids for looking up attributes and they are keys in the attr object. Therefore, they have to be strings in attr. So then you would need to convert them to strings at some point in order to look up the attributes.

> * in `attr` you use array for mode & profile; a key value (name:color) looks to me easier to read/handle. I know it will grow the size of the package, but for that we can do one letter as ket ("h" for homemaker) and in `attr` add a simple dict to translate one letter to full name.

I'm not sure I understand this comment. There are no arrays in 'attr', only key value pairs. I think the only differences in what you're suggesting here are (i) use letters instead of numbers as ids and (ii) changing the structure of the each object in "attr" from:
'''
{
  "id1": {
    "name": "name1",
    "color": "color1"
  },
  "id2": {
    "name": "name2",
    "color": "color2"
  },
  ...
}
'''
to:
'''
{
  "names": {
    "id1": "name1",
    "id2": "name2",
    ...
  },
  "colors": {
    "id1": "color1",
    "id2": "color2",
    ...
  }
}
'''
Regarding the id, I don't see much difference between using a number and a letter. If anything, using numbers can save on space because we can use ints in the actual trip data as you suggested above. Regarding the structure, I don't think there's much difference between the two options. If the second structure works better on your end, I'm ok to change to that.

If I haven't understood your suggestion properly, can you provide an example?
