### ISSUE TITLE
Add a way to create a report for the current table state

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_cityscopeJS#83]
There should be some way to download a report for the current table state which is ideally a csv and includes:
- for each interactive type, the square footages which have been added to the interactive area
- for each indicator, the raw value, normalised value and units (these can all now be found in the /indicators endpoint)

**Comment by RELNO** [comment]
@doorleyr looking at the way the indicators are built, it will create a beautiful spaghetti to try and collect data from each and consolidate it on the FE for a report. Options are: individual "download" button for radar, area calc, etc OR (cleaner solution) a cityio endpoint that holds these in one place

**Comment by doorleyr** [comment]
Ok, how about I just add the square meterages as new 'indicators' in the /indicators object. Since they shouldn't be added to charts, the viz-type property can be null so that you don't add them to any charts.

So the indicators object would be something like:
[{'name': 'average salary', 'value': 0.5, 'raw_value': 60000, 'units': 'USD', 'category': 'economic', 'viz-type': 'radar'},
...
...
{'name': 'Residential', 'value': 10000, 'raw_value': None, 'units': 'sq meters',  'category': 'land_uses', 'viz-type': None}
...
]
The FE would just need to take this one object and turn it into a csv. This would avoid creating a new end-point. It also makes some sense to think of square meterages as a very simple kind of indicator.

**Comment by RELNO** [comment]
See 3d551281fd6fdc271be80492b0e54c157589f42c. 
Looks like JSON=>CSV conversion is tricky when nested items are involved. for now it works, but more complex data structs might break.
Reopen if not sufficient

**Comment by doorleyr** [comment]
When I download the data, it's just a json dump with a '.csv' file extension. Also, it includes higher level keys "data", and "children" which are confusing.

**Comment by RELNO** [comment]
[yes, CSV conversion is not straight forward](https://stackoverflow.com/a/1872081/10220637).  I suggest sticking to JSON

**Comment by doorleyr** [comment]
Looking good now. Is it possible to remove the top level keys (data, children) and just return the actual data?
