### ISSUE TITLE
Minor Text Changes

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_cityscopeJS#86]
1) At the top of the layer selction panel, there is the text CityScopeJS. Can we change this to something like "CityScope Layers"

2) Can we add tooltips for the 4 icons on the top left of the main screen ( Select Layers, Edit Land Uses, and View Orientation and ??). The 4th button doesn't seem to do anything. Can it be removed if so?

**Comment by doorleyr** [comment]
If tooltips can't be added easily, just add static text for each icon instead.

**Comment by doorleyr** [comment]
nice. Just one spelling mistake: visability-> visibility.

**Comment by RELNO** [comment]
Open again if not done
