### ISSUE TITLE
502 Bad Gateway when requesting URL "https://cityio.media.mit.edu/api/table/update/CityScopeJS" 

### ISSUE THREAD

**Issue by SutaBeacon** [CityScope/CS_cityscopeJS#9]
Hi Ariel,
I encountered a Bad Gateway error as requesting the scanning results of lego-grids from the given URL to render the Radar component.
The problematic URL returning 502 is:
https://cityio.media.mit.edu/api/table/update/CityScopeJS

I upload the screenshot here. I assume it is caused by network accessibility. 
If I can bother you to fix the problem?
Thanks so much.
<img width="945" alt="502 error" src="https://user-images.githubusercontent.com/11718658/48414192-f3fddc80-e784-11e8-8ee5-ec91bff805b7.png">

**Comment by RELNO** [comment]
closing, same as https://github.com/CityScope/CS_cityscopeJS/issues/9
