### ISSUE TITLE
Create lineLayer example from trips 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_cityscopeJS#9]
https://deck.gl/#/documentation/deckgl-api-reference/layers/line-layer

**Comment by RELNO** [comment]
@doorleyr can you please sketch something?

**Comment by doorleyr** [comment]
@RELNO I put some data in the same format as the deckgl example here: https://cityio.media.mit.edu/api/table/grasbrook/test_line

Let me now how if you want more/less jitter or anything.

**Comment by RELNO** [comment]
done at https://github.com/CityScope/CS_cityscopeJS/commit/bc29be3cb9abde0868214f9590d0b933ce7f06ec. Still need to implement updates 
<img width="910" alt="Screen Shot 2019-11-08 at 12 13 57" src="https://user-images.githubusercontent.com/14296774/68496903-5a46ff00-0221-11ea-91dc-4bc38606f9e7.png">

**Comment by RELNO** [comment]
done @ https://github.com/CityScope/CS_cityscopeJS/commit/1f4e83af064a7ad5c06bdb9cf3520ff60b04a108
