### ISSUE TITLE
Failed prop type: Invalid prop `value` supplied to `ForwardRef(Slider)` on None type

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_cityscopeJS#98]
<img width="859" alt="Screen Shot 2020-08-11 at 12 00 40" src="https://user-images.githubusercontent.com/14296774/89920601-981aee80-dbca-11ea-8c14-c7a8b1c65d25.png">

**Comment by isoiso123** [comment]
i have the same problem did u find a solution ?

**Comment by RELNO** [comment]
@isoiso123 thanks for reporting. Please checkout current version #118 and let me know if this happens again

**Comment by RELNO** [comment]
closing for now, @isoiso123 feel free to reopen if V2 doesn't fix it.
